### ISSUE TITLE
A(20,2,add) 처리에 대해서

### ISSUE THREAD

**Issue by belhyun** [marpple/abc-functional-javascript#6]
A(20, 2, add) 에 대해서는 type exception이 발생하는데요.
A 함수 내부에서 매개변수에 대한 검증을 안한 것은 의도가 있는 동작인가요?

**Comment by indongyoo** [comment]
A는 apply처럼 쓰는 함수라 인자를 array나 arguments객체로 넘기기 위해 구현되어있습니다.
A([20, 2], add) 이렇게 쓰기 위해서요. add.apply(null, [20, 2]) 처럼요.
인자를 따로 넘기려고 할 경우 C(20, 2, add) 로 사용하시면 됩니다.

위 와 별개로 abcjs의 함수들은 인자 검증을 내부적으로 안하려고 하는 경향도 꽤 있는데요.
함수 하나에서 if 를 나누는것보다 애초에 2개의 함수를 만드는 걸 더 선호하는 편이기도 합니다.

**Comment by indongyoo** [comment]
이슈 등록 감사합니다 : )
의견 있으시면 주세요.
